// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bnihjitbgpfjedzwpxec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJuaWhqaXRiZ3BmamVkendweGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NzQ1NTMsImV4cCI6MjA1MDI1MDU1M30.sJwNlhxvxMyVXfEGdRQF9sCCIARGxP6_UlwJkj0W26g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);